### ISSUE TITLE
Could you add a link back to / on the confirmation page?

### ISSUE THREAD

**Issue by jameslittle230** [indirect/feedyour.email#22]
This project is great!! Hope it stays stable :)

Once I create a feed, I'd love to have a link that goes directly back to the creation form so I could easily make a few at a time.

Thanks for considering, feel free to instaclose if you don't want to do it :)

**Comment by indirect** [comment]
Thanks for the feedback! Can you say more about how it would be easier in your workflow to have a link back to the previous page instead of just hitting the Back button or ⌘[?

**Comment by jameslittle230** [comment]
Ya know, I honestly didn't even think about that.

I might have assumed that there would be weirdness around form submission - a lifetime of internet browsing has taught me to never trust the back button when web forms are involved.

I think I also just expected that part of the workflow to live within the application, instead of having to rely on the browser surrounding it?

Either way, back button is a good enough workaround. Thanks :)
