### ISSUE TITLE
Inline images do not render

### ISSUE THREAD

**Issue by numist** [indirect/feedyour.email#384]
Demonstrated by https://feedyour.email/posts/kay462mibxlmfny9ir2hgtyq

From the source, looks like there's a MIME attachment reference that obviously does not translate directly to web rendering `<img width="434" alt="PastedGraphic-1.png" src="cid:0C7C76F4-F224-4BB1-B3D5-2A92A1CCF277">`.

Slightly cranky about how this implies that every newsletter I've ever read (via FYE, at least) exclusively links to offsite images (and the tracking implications of such).

**Comment by numist** [comment]
Thinking out loud, fixing this is probably as easy as adding a mime library dependency, pulling out the attachments and then base 64 encoding them into the relevant `src="data:…` attributes

**Comment by indirect** [comment]
I mean, we could definitely add a processing step that pulls in external images and stores them ourselves and replaces the URLs! But then we are a binary asset host, so we would needs to limit possible abuse vectors etc. For whatever it's worth I do have an S3-alike account we could use for this, with a bunch of spare capacity.

**Comment by numist** [comment]
ugh actually we should probably add a trailing `/` to the post view and support requests to relative URL's below it via MIME lookup since that would also fix this same problem for linked attachments that are not rendered in line? action item: send a test email that includes a non-image attachment and see if it breaks any different.

**Comment by indirect** [comment]
the code to drop attachments into data URLs was short, and now we have no assets or files to manage: https://github.com/indirect/feedyour.email/pull/512/commits/997437f3179e5ce5c02c389b2ded4e4d3a495fed

**Comment by numist** [comment]
Hm, the [demonstration link](https://feedyour.email/posts/kay462mibxlmfny9ir2hgtyq) still doesn't seem to render correctly (in the feed nor on the web)

**Comment by indirect** [comment]
We do not and cannot ever render the demonstration link correctly, sorry. :( We have not been saving the full raw encoded email body with attachment bodies, only the HTML and plaintext parts. If you send a new email with attachments to a feed, they should get rendered inline now, though.
