### ISSUE TITLE
Consult gravatar et. al preferentially to the sender's domain's favicon

### ISSUE THREAD

**Issue by numist** [indirect/feedyour.email#43]
Assuming we get favicons working (hopefully with #42!), newsletters from platforms like substack are still likely to share boring favicons because their messages are still sent from the same domain. Maybe something like gravatar (and/or whatever exists to look up avatars for gmail/gapps accounts) could be consulted to provide some variety?

**Comment by indirect** [comment]
substack gives each newsletter a subdomain and a fancy logo, wouldn’t that do it? I do think it’s a good idea as a fallback though

**Comment by numist** [comment]
If they do, it doesn't seem to be reflected in the sending email addresses (todayintabs@substack.com and garbageday@substack.com being two examples)… should we be mining the content of the emails for clues?

**Comment by indirect** [comment]
I guess it means we special case substack to attach the address as a subdomain? Blech.

**Comment by numist** [comment]
Yeah if we continue down this path there's going to be a _lot_ of special cases.

**Comment by indirect** [comment]
Substack definitely does not set gravatars for any of their source email addresses: https://en.gravatar.com/site/check/
