### ISSUE TITLE
May I ask how to reply email?

### ISSUE THREAD

**Issue by DophinL** [indirect/feedyour.email#466]
<img width="668" alt="image" src="https://github.com/indirect/feedyour.email/assets/8707316/7dec0bd9-66d4-4fcc-9da6-e810debeea8d">

**Comment by indirect** [comment]
We do not have any way to send emails at this time, sorry.

**Comment by numist** [comment]
One workaround is to use your own email address for the newletter and use a server side mail rule to forward it to feedyour.email (and archive/mark as read/delete).
